import { ChristmasPuzzleLinks, MemoryGameLinks, PuzzleLinks } from "../types/enums"

// Keywords
export const KEYWORDS = ['arsenkids', 'արսենքիդս', 'kids', 'education', 'armenian', 'children', 'educational', 'կրթական', 'մանկական', 'հետաքրքիր', 'ուսուցողական', 'ուսուցողական թերթեր', 'մանկական երգեր', 'մանկական վիդեոներ', 'մանկական տեսանյութեր', 'հետաքրքիր մանկական', 'ինտելեկտուալ', 'intellectual', 'toddlers', 'interesting', 'interesting videos', 'learning', 'learning videos', 'զարգացնել հիշողությունը,հիշողությունը զարգացնող տեսանյութեր', 'թվաբանություն', 'մաթեմատիկա', 'գումարում', 'հանում', 'բազմապատկում', 'բաժանում', 'այբուբեն', 'երկրաչափական պատկերներ', 'երկրաչափական մարմիններ', 'կենդանիներ', 'տրանսպորտային միջոցներ', 'զարգացնող', 'mankakan', 'krtakan', 'usucoxakan', 'hetaqrqir', 'arsenkids aliq', 'hayeren', 'հայերեն', 'հայկական', 'haykakan', 'haykakan aliq', 'haykakan mankakan', 'հայկական մանկական', 'armenian kids', 'armenian children', 'armenian educational', 'armenian channel', "colors", "animals", "learn colors", "guynner", "sovorel guynner", "գույններ", "սովորել գույններ", "այբուբեն", "aybuben", "hayeren aybuben", "հայերեն այբուբեն"]
export const GAME_KEYWORDS = ["arsenkids games", "արսենքիդս խաղեր", "մանկական խաղեր", "հետաքրքիր խաղեր", "educational games", "educational online games for kids", "educational games for toddlers", "օնլայն խաղեր", "օնլայն մանկական խաղեր", "խաղեր", "մանկական հետաքրքիր խաղեր", "իքսիկ նոլիկ", "memory games", "հիշողությունը զարգացնող խաղեր", "մաթեմատիկական խաղեր", "թվաբանական խաղեր", "xaxer", "hetaqrqir xaxer", "mankakan xaxer", "usucoxakan xaxer", "ուսուցողական խաղեր", "arsenkids xaxer", "hayeren xaxer", "hayeren erexeqi xaxer", "hayeren mankakan xaxer", "armenian games", "armenian online games", "armenian educational games", "ixik nolik", "online xaxer", "haykakan online xaxer", "kids games", "ժամանցային", "jamancayin xaxer", "jamancayin", "hishoxutyuny zargacnox xaxer", "mankakan online xaxer", "tic tac toe", "guess the word"]

// Links
export const PUZZLE_LINKS = Object.values(PuzzleLinks)
export const CHRISTMAS_PUZZLE_LINKS = Object.values(ChristmasPuzzleLinks)
export const PAIRS_LINKS = Object.values(MemoryGameLinks)