import { ISnowmanItem, ISnowmanSidebar } from "../types"

export const snowmanItems:ISnowmanItem[] = [
     {name: "",type: "eye"},
     {name: "eye-1", type: "eye"},
     {name: "eye-2", type: "eye"},
     {name: "eye-3", type: "eye"},
     {name: "eye-4", type: "eye"},
     {name: "eye-5", type: "eye"},
     {name: "eye-6", type: "eye"},
     {name: "", type: "nose"},
     {name: "nose-1", type: "nose"},
     {name: "nose-2", type: "nose"},
     {name: "", type: "mouth"},
     {name: "mouth-1", type: "mouth"},
     {name: "mouth-2", type: "mouth"},
     {name: "mouth-3", type: "mouth"},
     {name: "", type: "hat"},
     {name: "beanie", type: "hat"},
     {name: "boater", type: "hat"},
     {name: "bucket", type: "hat"},
     {name: "cap", type: "hat"},
     {name: "cowboy", type: "hat"},
     {name: "elf", type: "hat"},
     {name: "santa", type: "hat"},
     {name: "top", type: "hat"},
     {name: "", type: "hand"},
     {name: "stick-1", type: "hand"},
     {name: "stick-2", type: "hand"},
     {name: "stick-3", type: "hand"},
     {name: "mitten", type: "hand"},
     {name: "", type: "button"},
     {name: "buttons-1", type: "button"},
     {name: "buttons-2", type: "button"},
     {name: "buttons-3", type: "button"},
     {name: "buttons-4", type: "button"},
     {name: "buttons-5", type: "button"},
     {name: "buttons-6", type: "button"},
     {name: "buttons-7", type: "button"},
]
export const snowmanSidebarItems: ISnowmanSidebar[] = [
     { title: "Աչքեր", type: "eye" },
     { title: "Քթեր", type: "nose" },
     { title: "Բերան", type: "mouth" },
     { title: "Գլխարկ", type: "hat" },
     { title: "Ձեռքեր", type: "hand" },
     { title: "Կոճակներ", type: "button" }
]